#List of contractions and corresponding expansions

italian_contractions = {
"l'": "il",
"del": "di il",
"dello": "di lo",
"dell'": "di il",
"dei": "di i",
"degli": "di gli",
"delle": "di le",
"col": "con il",
"coi": "con i",
"coll'": "con il",
"collo": "con lo",
"cogli": "con gli",
"colla": "con la",
"colle": "con le",
"al": "a il",
"allo": "a lo",
"alla": "a la",
"all'": "a il",
"ai": "a i",
"agli": "a gli",
"alle": "a le",
"sul": "su il",
"sulla": "su la",
"sullo": "su lo",
"sugli": "su gli",
"sull'": "su il",
"sulle": "su le",
"sui": "su i",
"nei": "in i",
"nel": "in il",
"nella": "in la",
"nell'": "in il",
"nello": "in lo",
"dal": "da il",
"dalle": "da le",
"dalla": "da la",
"dall'": "da il",
"dallo": "da lo",
"dagli": "da gli",
"nelle": "in le",
"negli": "in gli",
"nello": "in lo",
"nell'": "in il",
"nel": "in il"
}
