#List of contractions and corresponding expansions

german_contractions = {
"am": "an dem",
"ans": "an das",
"aufs": "auf das",
"beim": "bei dem",
"durchs": "durch das",
"fürs": "für das",
"hinterm": "hinter dem",
"ins": "in das",
"im": "in dem",
"übers": "über das",
"ums": "um das",
"unters": "unter das",
"unterm": "unter dem",
"vom": "von dem",
"vors": "vor das",
"vorm": "vor dem",
"zum": "zu dem",
"zur": "zu der",
"'n": "ein",
"'ne": "eine",
"'nem": "einem",
"'ner": "einer",
"'s": "is",
"beym": "beim",
"drum": "darum",
"ei'm": "einem",
"eim": "einem",
"gab's": "gab es",
"geht's": "geht es",
"gehts": "geht es",
"gibt's": "gibt es",
"Gnad'": "Gnade",
"g'rade": "gerade",
"hab's": "habe es",
"hammer": "haben wir",
"hinters": "hinter es",
"inner": "in der",
"mim": "mit dem",
"nem": "einem",
"ner": "einer",
"siehste": "siehst du",
"siehstu": "siehst du",
"simmer": "sind wir",
"so'n": "so ein",
"sone": "so eine",
"sowas": "so etwas",
"so'nes": "so eines",
"so'nem": "so einem",
"so'nen": "so einen",
"so'ne": "so eine",
"so'ner": "so einer",
"vom": "von dem",
"vorm": "vor dem",
"vors": "vor das",
"war's": "war es",
"wär's": "wär es",
"weißtu": "weißt du",
"zun": "zu den",
"hab": "habe",
"hab'": "habe"
}

